name: Docker Image CI (Upload Tag)

on:
  push:
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4 # Updated from v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3 # Recommended for multi-platform builds

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 # Updated from v1

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5 # Updated from v4
      with:
        images: amirpourmand/al-folio

    - name: Login to Docker Hub
      uses: docker/login-action@v3 # Updated from v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5 # Updated from v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max