name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.repository_owner == 'alshedivat'

    steps:
    - name: Checkout
      uses: actions/checkout@v4 # Updated from v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3 # Recommended for multi-platform builds

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 # Updated from v1

    - name: Login to Docker Hub
      uses: docker/login-action@v3 # Updated from v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5 # Updated from v2
      with:
        context: .
        push: true
        tags: amirpourmand/al-folio:latest # Added :latest tag for clarity
        cache-from: type=gha
        cache-to: type=gha,mode=max
